packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@scarf/scarf': false
  esbuild: true

dedupePeers: true
dedupePeerDependents: true
resolvePeersFromWorkspaceRoot: true

overrides:
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  '@sveltejs/kit>cookie': 0.7.2
  proxy-addr: 2.0.8
  brace-expansion@5: 5.0.12
  devalue: 5.9.3
  source-map-js: 1.2.2
  multer: 2.4.0
  fast-uri@3: 3.1.8
  fast-uri@4: 4.1.5
  fastify: 5.12.5
